### ISSUE TITLE
Can't add new host via Web UI

### ISSUE THREAD

**Issue by morevnaproject** [tiredofit/docker-backuppc#1]
I get "500 Internal Server Error" after navigating to "Edit Hosts" (in left menu) and then clicking "Add" button.

![screenshot_001](https://user-images.githubusercontent.com/332868/51977944-5da3a200-24bb-11e9-93a9-74b973db8e1e.png)

(on the screenshot you can see there are already some hosts available - I have added them by editing config file).

The same "500 Internal Server Error" also appears in other places, when I am trying to edit configuration o particular hosts.

**Comment by morevnaproject** [comment]
I tried to update Docker file to BackupPC 4.3.0, but the problem remains. Looks like this is a problem with nginx configuration.

**Comment by tiredofit** [comment]
Hi I've just moved my private codebase onto this github variant. Docker Hub is building a new release now. Can you see if you still experience the issue (this will also update to 4.3.0)

**Comment by morevnaproject** [comment]
Hey, thank you for a quick response! Will test now. ^__^

**Comment by morevnaproject** [comment]
Um, scratch my comment. I forgot to run "docker pull". ^__^"

**Comment by morevnaproject** [comment]
Works perfectly now! Now I am happy owner of BackupPC instance with Zabbix agent. Thank you! ^__^

**Comment by tiredofit** [comment]
Fantastic! Enjoy, we've been using in production for 2 years now with great success.

**Comment by morevnaproject** [comment]
Thank you for your work! ^__^
