### ISSUE TITLE
Backuppc service doesn't starts

### ISSUE THREAD

**Issue by morevnaproject** [tiredofit/docker-backuppc#3]
I am trying to start from latest image at tiredofit/backuppc.

Got the following error when entering web UI:
![screenshot_002](https://user-images.githubusercontent.com/332868/78224980-a0b03980-74f3-11ea-8c55-8b113e465c35.png)

I have enabled DEBUG_MODE and see that backuppc service is stuck in the following loop:
```
...
backuppc                 | [DEBUG] /run/s6/services/20-backuppc/run ** [backuppc] Looking for existence of /tmp/state/11-fcgiwrap-init
backuppc                 | + '[' '!' -f /tmp/state/11-fcgiwrap-init ']'
backuppc                 | + sleep 1
backuppc                 | + print_debug 'Looking for existence of /tmp/state/11-fcgiwrap-init'
backuppc                 | + output_off
backuppc                 | + '[' TRUE = TRUE ']'
backuppc                 | + set +x
backuppc                 | [DEBUG] /run/s6/services/20-backuppc/run ** [backuppc] Looking for existence of /tmp/state/11-fcgiwrap-init
backuppc                 | + '[' '!' -f /tmp/state/11-fcgiwrap-init ']'
backuppc                 | + sleep 1
backuppc                 | + print_debug 'Looking for existence of /tmp/state/11-fcgiwrap-init'
backuppc                 | + output_off
backuppc                 | + '[' TRUE = TRUE ']'
backuppc                 | + set +x
backuppc                 | [DEBUG] /run/s6/services/20-backuppc/run ** [backuppc] Looking for existence of /tmp/state/11-fcgiwrap-init
backuppc                 | + '[' '!' -f /tmp/state/11-fcgiwrap-init ']'
backuppc                 | + sleep 1
backuppc                 | + print_debug 'Looking for existence of /tmp/state/11-fcgiwrap-init'
backuppc                 | + output_off
backuppc                 | + '[' TRUE = TRUE ']'
backuppc                 | + set +x
backuppc                 | [DEBUG] /run/s6/services/20-backuppc/run ** [backuppc] Looking for existence of /tmp/state/11-fcgiwrap-init
...
```

Any help is appreciated. ^__^

**Comment by morevnaproject** [comment]
As temporary solution I have commented line 7 in this file:

https://github.com/tiredofit/docker-backuppc/blob/9b272bb0e5c96c9931b7ffada3ce1dbb66b13247/install/etc/s6/services/20-backuppc/run#L4-L8

After that container works well for me.

**Comment by tiredofit** [comment]
I'll push a patch shortly with these changes thanks for identifying. This must have snuck in when I changed my base images around.

**Comment by tiredofit** [comment]
Resolved - I had it fixed a few weeks ago on my private repositories but neglected to update this public one. A few other enhancements and bugfixes since I've last pushed, let me know if this works for you!

**Comment by morevnaproject** [comment]
Apologies for such a long delay. I just tested it and works perfectly! Thank you so much! ^__^
