### ISSUE TITLE
missing /etc/msmtprc

### ISSUE THREAD

**Issue by kunago** [tiredofit/docker-backuppc#8]
I just updated to the newest docker image and there seems to be some issue with folder /etc/msmtprc. This is the log loop:

```
cp: can't stat '/etc/msmtprc': No such file or directory
[INFO] ** [backuppc] Starting BackupPC 4.4.0
```

I assume it is crashing here:
https://github.com/tiredofit/docker-backuppc/blob/fe7ddbe4f5472b930ef387dc5d90b4e7ca81ef6a/install/etc/services.available/20-backuppc/run#L10

**Comment by tiredofit** [comment]
Weird. I can't recreate it. 
Do you have `ENABLE_SMTP=FALSE` set at all in your docker compose/docker environment variables?

I will add a smoke test for that command anyways  just to hide the error if SMTP is off, and move it to a better part of the image.

**Comment by tiredofit** [comment]
Should be resolved now!
