### ISSUE TITLE
Bad URL in readme.md

### ISSUE THREAD

**Issue by prabbit237** [tiredofit/docker-backuppc#9]
The section reading:

````
Installation
Automated builds of the image are available on [Docker Hub](https://tiredofit/r/backuppc) and is the recommended method of installation.

docker pull tiredofit/backuppc
````
has a typo in the URL. The URL linked from "Docker Hub" points to https://tiredofit/r/backuppc and should point to https://hub.docker.com/r/tiredofit/backuppc/

**Comment by tiredofit** [comment]
Fixed thank you :)
